# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CMNETwinUpload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_TE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_route', models.CharField(max_length=100, verbose_name='主路由')),
                ('standby_route', models.CharField(max_length=100, verbose_name='备路由')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'IP_TE主备LSP',
                'verbose_name_plural': 'IP_TE主备LSP',
                'db_table': 'e_IP_TE',
            },
        ),
        migrations.CreateModel(
            name='IPMalfunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raleyCircuitid', models.BigIntegerField(verbose_name='中继电路操作ID')),
                ('fid', models.BigIntegerField(verbose_name='中继电路文件ID')),
                ('file_path', models.CharField(max_length=200, verbose_name='中继电路文件路径')),
                ('filename', models.CharField(max_length=100, verbose_name='中继电路文件名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMNETwinUpload.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'IP_故障轮巡',
                'verbose_name_plural': 'IP_故障轮巡',
                'db_table': 'e_IPMalfunction',
            },
        ),
        migrations.CreateModel(
            name='IPMetricTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.BigIntegerField(verbose_name='metric操作ID')),
                ('fid', models.BigIntegerField(verbose_name='metric文件ID')),
                ('file_path', models.CharField(max_length=200, verbose_name='metric文件路径')),
                ('filename', models.CharField(max_length=100, verbose_name='metric文件名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMNETwinUpload.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'IP_metric操作',
                'verbose_name_plural': 'IP_metric操作',
                'db_table': 'e_IPMetricTable',
            },
        ),
        migrations.CreateModel(
            name='IpNodes_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province1', models.CharField(max_length=20, verbose_name='本工程前省份')),
                ('node1', models.CharField(max_length=20, verbose_name='本工程前节点')),
                ('office_address1', models.CharField(max_length=50, verbose_name='本工程前局址')),
                ('building_no1', models.CharField(max_length=20, verbose_name='本工程前楼号')),
                ('floor1', models.CharField(max_length=20, verbose_name='本工程前楼层')),
                ('room_num1', models.CharField(max_length=20, verbose_name='本期前机房编号')),
                ('plane1', models.CharField(max_length=10, verbose_name='本工程前流量平面')),
                ('part1', models.CharField(max_length=20, verbose_name='本工程前角色')),
                ('network_level1', models.CharField(max_length=20, verbose_name='本期前网络层次')),
                ('province2', models.CharField(max_length=20, verbose_name='本工程后省份')),
                ('node2', models.CharField(max_length=20, verbose_name='本工程后节点')),
                ('office_address2', models.CharField(max_length=50, verbose_name='本工程后局址')),
                ('building_no2', models.CharField(max_length=20, verbose_name='本工程后楼号')),
                ('floor2', models.CharField(max_length=20, verbose_name='本工程后楼层')),
                ('room_num2', models.CharField(max_length=20, verbose_name='本期后机房编号')),
                ('plane2', models.CharField(max_length=10, verbose_name='本工程后流量平面')),
                ('part2', models.CharField(max_length=20, verbose_name='本工程后角色')),
                ('network_level2', models.CharField(max_length=20, verbose_name='本期后网络层次')),
                ('program', models.CharField(max_length=30, verbose_name='建设方案')),
            ],
            options={
                'verbose_name': 'IP节点信息',
                'verbose_name_plural': 'IP节点信息',
                'db_table': 'e_IpNodes_detail',
            },
        ),
        migrations.CreateModel(
            name='IPPtoPoint_flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowid', models.BigIntegerField(verbose_name='点到点流量操作ID')),
                ('fid', models.BigIntegerField(verbose_name='点到点流量文件ID')),
                ('file_path', models.CharField(max_length=200, verbose_name='点到点流量文件路径')),
                ('filename', models.CharField(max_length=100, verbose_name='点到点流量文件名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMNETwinUpload.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'IP_点到点流量',
                'verbose_name_plural': 'IP_点到点流量',
                'db_table': 'e_IPPtoPoint_flow',
            },
        ),
        migrations.CreateModel(
            name='IPPtoPoint_route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeid', models.BigIntegerField(verbose_name='点点路由操作ID')),
                ('fid', models.BigIntegerField(verbose_name='点点路由文件ID')),
                ('file_path', models.CharField(max_length=200, verbose_name='点点路由文件路径')),
                ('filename', models.CharField(max_length=100, verbose_name='点点路由文件名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMNETwinUpload.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'IP_点点路由',
                'verbose_name_plural': 'IP_点点路由',
                'db_table': 'e_IPPtoPoint_route',
            },
        ),
        migrations.CreateModel(
            name='IPRelay_circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raleyCircuitid', models.BigIntegerField(verbose_name='中继电路操作ID')),
                ('fid', models.BigIntegerField(verbose_name='中继电路文件ID')),
                ('file_path', models.CharField(max_length=200, verbose_name='中继电路文件路径')),
                ('filename', models.CharField(max_length=100, verbose_name='中继电路文件名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMNETwinUpload.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'IP_中继电路',
                'verbose_name_plural': 'IP_中继电路',
                'db_table': 'e_IPRelay_circuit',
            },
        ),
        migrations.CreateModel(
            name='IPRelay_traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raleyid', models.BigIntegerField(verbose_name='中继转发流量操作ID')),
                ('fid', models.BigIntegerField(verbose_name='中继转发流量文件ID')),
                ('file_path', models.CharField(max_length=200, verbose_name='中继转发流量文件路径')),
                ('filename', models.CharField(max_length=100, verbose_name='中继转发流量文件名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMNETwinUpload.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'IP_中继转发流量',
                'verbose_name_plural': 'IP_中继转发流量',
                'db_table': 'e_IPRelaying_traffic',
            },
        ),
    ]
